--- git-1.7.1/Makefile.orig	2010-04-24 02:38:35.000000000 +0000
+++ git-1.7.1/Makefile	2010-04-25 21:35:04.982729569 +0000
@@ -246,7 +246,7 @@
 
 CFLAGS = -g -O2 -Wall
 LDFLAGS =
-ALL_CFLAGS = $(CFLAGS)
+ALL_CFLAGS = $(CFLAGS) $(CPPFLAGS)
 ALL_LDFLAGS = $(LDFLAGS)
 STRIP ?= strip
 
@@ -1543,7 +1543,7 @@
 	$(QUIET_GEN)$(RM) $@ $@+ && \
 	INSTLIBDIR=`MAKEFLAGS= $(MAKE) -C perl -s --no-print-directory instlibdir` && \
 	sed -e '1{' \
-	    -e '	s|#!.*perl|#!$(PERL_PATH_SQ)|' \
+	    -e '	s|#!.*perl|#!/opt/bin/perl|' \
 	    -e '	h' \
 	    -e '	s=.*=use lib (split(/$(pathsep)/, $$ENV{GITPERLLIB} || "@@INSTLIBDIR@@"));=' \
 	    -e '	H' \
@@ -1597,7 +1597,7 @@
 	    -e '/@@GITWEB_CSS@@/d' \
 	    -e '/@@GITWEB_JS@@/r $(GITWEB_JS)' \
 	    -e '/@@GITWEB_JS@@/d' \
-	    -e 's|@@PERL@@|$(PERL_PATH_SQ)|g' \
+	    -e 's|@@PERL@@|/opt/bin/perl|g' \
             -e 's|@@GITWEB_CSS_NAME@@|$(GITWEB_CSS)|' \
             -e 's|@@GITWEB_JS_NAME@@|$(GITWEB_JS)|' \
 	    $@.sh > $@+ && \
@@ -1992,9 +1992,7 @@
 		cp "$$bindir/git$X" "$$execdir/git$X"; } ; } && \
 	{ for p in $(BUILT_INS); do \
 		$(RM) "$$execdir/$$p" && \
-		ln "$$execdir/git$X" "$$execdir/$$p" 2>/dev/null || \
-		ln -s "git$X" "$$execdir/$$p" 2>/dev/null || \
-		cp "$$execdir/git$X" "$$execdir/$$p" || exit; \
+		ln -s "git$X" "$$execdir/$$p" 2>/dev/null || exit; \
 	  done; } && \
 	{ for p in $(REMOTE_CURL_ALIASES); do \
 		$(RM) "$$execdir/$$p" && \
