LIBC_STYLE=glibc
TARGET_ARCH=mipsel
TARGET_OS=linux-gnu

#LIBNSL_VERSION=0.9.19

#GETTEXT_NLS=enable
#STAGING_CPPFLAGS+= -DMB_CUR_MAX=1

#STAGING_PREFIX=$(STAGING_DIR)/usr/local
LIBSTDC++_VERSION=6.0.10

HOSTCC = gcc
GNU_HOST_NAME = $(HOST_MACHINE)-pc-linux-gnu
GNU_TARGET_NAME = mipsel-linux
CROSS_CONFIGURATION = mipsel-unknown-linux-gnu
TARGET_CROSS_TOP = $(HOME)/x-tools/$(CROSS_CONFIGURATION)
TARGET_CROSS = $(TARGET_CROSS_TOP)/bin/$(CROSS_CONFIGURATION)-
TARGET_LIBDIR = $(TARGET_CROSS_TOP)/lib
TARGET_INCDIR = $(TARGET_CROSS_TOP)/include
TARGET_LDFLAGS = 
TARGET_CUSTOM_FLAGS= -pipe -fPIC -march=mips32r2 
#-D_GNU_SOURCE
TARGET_CFLAGS=$(TARGET_OPTIMIZATION) $(TARGET_DEBUGGING) $(TARGET_CUSTOM_FLAGS)
LIBSTDC++_TARGET_LIBDIR = $(TARGET_CROSS_TOP)/$(CROSS_CONFIGURATION)/sysroot/lib


toolchain:

