LIBC_STYLE=glibc
TARGET_ARCH=mipsel
TARGET_OS=linux-gnu
OPTWARE_PREFIX=/usr/local

#LIBNSL_VERSION=0.9.19

#GETTEXT_NLS=enable
#STAGING_CPPFLAGS+= -DMB_CUR_MAX=1

#STAGING_PREFIX=$(STAGING_DIR)/usr/local
LIBSTDC++_VERSION=6.0.10
LIBNSL_VERSION=2.8
PERL_MAJOR_VER = 5.10
LIBDB_LDFLAGS=-lpthread

HOSTCC = $(TARGET_CC)
GNU_HOST_NAME = mipsel-unknown-linux-gnu
GNU_TARGET_NAME=mipsel-unknown-linux-gnu
TARGET_PREFIX=/root/x-tools/mipsel-unknown-linux-gnu
TARGET_CROSS=$(TARGET_PREFIX)/bin/$(GNU_TARGET_NAME)-
TARGET_LIBDIR=$(TARGET_PREFIX)/lib
TARGET_INCDIR=$(TARGET_PREFIX)/include
TARGET_LDFLAGS = -L$(TARGET_LIBDIR)
TARGET_CUSTOM_FLAGS= -pipe -fPIC 
TARGET_CFLAGS=$(TARGET_OPTIMIZATION) $(TARGET_DEBUGGING) $(TARGET_CUSTOM_FLAGS)
TARGET_USRLIBDIR=$(TARGET_PREFIX)/$(GNU_TARGET_NAME)/sysroot/usr/lib
LIBSTDC++_TARGET_LIBDIR = $(TARGET_PREFIX)/$(GNU_TARGET_NAME)/lib
LIBNSL_SO_DIR = $(TARGET_PREFIX)/$(GNU_TARGET_NAME)/lib
STAGING_CFLAGS=$(TARGET_CUSTOM_FLAGS)
STAGING_CPPFLAGS=$(STAGING_CFLAGS)


toolchain:

